export const MOCK_USERS = [
  {
    uuid: "u-1001",
    name: "Sok Cheat Srorng",
    email: "sokcheatsrorng@gmail.com",
    role: "Admin",
    status: "active",
    joinedAt: "2024-01-15",
  },
  {
    uuid: "u-1002",
    name: "Jane Mitchell",
    email: "jane.mitchell@example.com",
    role: "Supplier",
    status: "active",
    joinedAt: "2024-02-03",
  },
  {
    uuid: "u-1003",
    name: "Robert Chen",
    email: "robert.chen@example.com",
    role: "Manager",
    status: "active",
    joinedAt: "2024-03-21",
  },
  {
    uuid: "u-1004",
    name: "Maria Garcia",
    email: "maria.garcia@example.com",
    role: "User",
    status: "pending",
    joinedAt: "2024-04-11",
  },
  {
    uuid: "u-1005",
    name: "David Wilson",
    email: "david.wilson@example.com",
    role: "User",
    status: "active",
    joinedAt: "2024-05-02",
  },
  {
    uuid: "u-1006",
    name: "Emily Davis",
    email: "emily.davis@example.com",
    role: "User",
    status: "inactive",
    joinedAt: "2024-05-27",
  },
  {
    uuid: "u-1007",
    name: "James Brown",
    email: "james.brown@example.com",
    role: "Supplier",
    status: "active",
    joinedAt: "2024-06-09",
  },
  {
    uuid: "u-1008",
    name: "Sophia Miller",
    email: "sophia.miller@example.com",
    role: "Manager",
    status: "active",
    joinedAt: "2024-07-18",
  },
  {
    uuid: "u-1009",
    name: "Michael Moore",
    email: "michael.moore@example.com",
    role: "User",
    status: "inactive",
    joinedAt: "2024-08-04",
  },
  {
    uuid: "u-1010",
    name: "Olivia Taylor",
    email: "olivia.taylor@example.com",
    role: "User",
    status: "pending",
    joinedAt: "2024-09-22",
  },
  {
    uuid: "u-1011",
    name: "William Anderson",
    email: "william.anderson@example.com",
    role: "User",
    status: "active",
    joinedAt: "2024-10-13",
  },
  {
    uuid: "u-1012",
    name: "Isabella Thomas",
    email: "isabella.thomas@example.com",
    role: "Supplier",
    status: "active",
    joinedAt: "2024-11-01",
  },
];
